### ISSUE TITLE
Are Pointer width dependent types correct?

### ISSUE THREAD

**Issue by denzp** [japaric/cty#2]
Shouldn't `c_int` and `c_uint` be always 32-bit?

I think `c_long` and `c_ulong` should really depend on `target_pointer_width`.

**Comment by japaric** [comment]
I believe these are correct for the architectures that Rust officially supports as they come from the libc crate. They may not be correct for AVR or MSP430 though.

cc @pftbest @awygle Do the definition in [here] look correct for the MSP430?

[here]: https://github.com/japaric/cty/blob/master/src/lib.rs

**Comment by denzp** [comment]
@japaric Yes, could be. I only know *x86* and *x86_64* case. But we must take into account that always `sizeof(c_long) >= sizeof(c_int)`.

Also, I found that libc and **std** use `c_int = i32`:
- https://doc.rust-lang.org/src/std/os/raw.rs.html#39
- https://github.com/rust-lang/libc/blob/master/src/lib.rs#L119

**Comment by japaric** [comment]
Oh, you are totally right. I had confused c_int with intptr_t. c_int *is* 32 bits on all officially supported Rust targets.

**Comment by denzp** [comment]
What about **c_long**? At least on:
x86: `sizeof(c_long) = 4`
x86_64: `sizeof(c_long) = 8`

But I'm not sure if we could rely on `target_pointer_width` in general, or other architectures might not have this rule...

**Comment by japaric** [comment]
Looking at the libc crate. It seems that most *nix targets (Haiku, macOS, Linux, Android, *BSD) agree that `c_{,u}long` matches `usize` in size. Windows seem to conside `c_{,u}long` to always be 32 bits, and both Solaris and Redox consider it to be always 64 bits. IDK about NVPTX and other bare metal targets like MSP430 and AVR.

**Comment by awygle** [comment]
For MSP430, in the small model (let's not bother with large for now), we should end up with this:

pub type c_int = i16;
pub type c_long = i32;
pub type c_longlong = i64;
pub type c_schar = i8;
pub type c_short = i16;
pub type c_uchar = u8;
pub type c_uint = u16;
pub type c_ulong = u32;
pub type c_ulonglong = u64;
pub type c_ushort = u16;

So the only thing that changes is that the int types are 16 bit.

EDIT: at least, the above is true with GCC - isn't this a compiler-specific rather than platform-specific thing?

**Comment by pftbest** [comment]
@awygle, do you remember​ is `char` signed or unsigned?

**Comment by awygle** [comment]
Without passing any flags, char is unsigned by default.

**Comment by japaric** [comment]
@awygle Hmm, `clang` 4.0 seems to assume that char = i8:

``` console
$ cat foo.c
void foo(char c) {
  char b = 128;
}

$ clang --target=msp430 -Werror -c foo.c
foo.c:2:12: error: implicit conversion from 'int' to 'char' changes value from 128 to -128 [-Werror,-Wconstant-conversion]
  char b = 128;
       ~   ^~~
1 error generated.

$ clang --target=arm-none-eabi -Werror -c foo.c && echo OK
OK
```

**Comment by japaric** [comment]
OTOH, `msp430-elf-gcc` assumes `char` is `u8`

``` console
$ msp430-elf-gcc -c -Wconversion -Werror foo.c && echo OK
OK

$ gcc -c -Wconversion -Werror foo.c
foo.c: In function ‘foo’:
foo.c:2:12: error: conversion to ‘char’ alters ‘int’ constant value [-Werror=conversion]
   char b = 128;
            ^~~
cc1: all warnings being treated as errors
```

**Comment by japaric** [comment]
> The char type is unsigned by default.

From [MSP430 Embedded Application Binary Interface - Application Report](http://www.ti.com/lit/an/slaa534/slaa534.pdf). I'll go with `u8` then.

**Comment by japaric** [comment]
I think this issue has been solved already.
